name: GitHub Actions Demo
on: [push]
jobs:
  # shellcheck:
  #   name: Shellcheck
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: ShellCheck
  #       run: shellcheck -x $(find . -name '*.sh')

  # lint:
  #   name: Lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Setup Go
  #       uses: actions/setup-go@v3
  #       with:
  #         go-version-file: go.mod
  #         cache: true
  #     - name: go build deps
  #       run: make embed-files-test
  #     - name: golangci-lint
  #       uses: golangci/golangci-lint-action@v3
  #       with:
  #         version: latest
  #         skip-pkg-cache: true

  govulncheck:
    name: Go Vulnerabilities Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
      - name: Install govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
      - name: Build OSM
        run: make build-osm
      - name: go vulnerabilities check
        run: |
          free -m
          # osmModules=$(go list ./...)
          # moduleArray=$(echo $osmModules | tr "\n" "\n")
          # for module in $moduleArray
          # do
          #     govulncheck $module
          # done

# jobs:
#   Explore-GitHub-Actions:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
#       - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
#       - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
#       - name: Check out repository code
#         uses: actions/checkout@v3
#       - run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
#       - run: echo "üñ•Ô∏è The workflow is now ready to test your code on the runner."
#       - name: Check go vulnerabilities in the repository
#         run: |
#           go version
#       - run: echo "üçè This job's status is ${{ job.status }}."
